# Sidebar menu
menu:
  home: /
  archives: /archives
  categories: /categories
  tags: /tags
  # about: /about

# Routes for custom pages
page:
  - about?
  # Multi-level route example
  # - awesome-stuff:
  #   - chapter-1
  #   - chapter-2

# Profile
profile:
  # Email address will be used for showing gravatar(https://en.gravatar.com) avatar.
  email: example@mail.com
  bio: Awesome guy.

# Social media
sns:
  github: https://github.com/yourname
  twitter: https://twitter.com/yourname
  gplus: https://plus.google.com/u/0/xxx
  weibo: http://weibo.com/yourname

# Copyright
copyright: ©2018

# Disqus comments
# disqus:
  # shortname: your_disqus_shortname
  # Set to true to auto load disqus, otherwise will display a button
  # autoload: true

# Assets path
assets:
  prefix: 'https://cdn.example.com'
  suffix: '?m=webp&q=80'

# Meta Theme Color
# color: '#111'

### Pagination size
# The amount of posts displayed on a single archive/tag/category page, default is `10`, set to `0` to disable pagination.
archive:
  per_page: 10
tag:
  per_page: 10
category:
  per_page: 10

# Google analytics
# ga: UA-00000000-0

# Default thumbnail
# thumbnail: /writting.jpg